---
title: "Blog"
---

# 

#Blog

I have chosen to complete my Graduate studies in Canada for several reasons including the diversity within the country, the high academic standards and the quality of education that is globally recognized. Moreover, I specifically selected the University of Winnipeg due to the quality of education that is given at an affordable price, the professor to student ratio where I will have more opportunity to connect with the faculty members efficiently, and most importantly the MAE program that aligns well with my educational and career objective by specializing in research in analyzing the interaction of social, environmental, and economic issues globally.

Thus, completing my studies in Canada will not only provide me an exceptional graduate student experience but also make my credentials more competitive in the job market back home in my home country working in public and/or private sectors, international companies and agencies as the Canadian experience and education are highly valued worldwide.
